import './globals.css'
import { Inter } from 'next/font/google'
// import Navbar from '../components/common'
import Navbar from './components/common/Navbar'
import Footer from './components/common/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div
        className='px-[2%] md:px-[6%] 2xl:mx-auto 2xl:container 2xl:!px-0
         min-h-screen pt-20'
        >

        {children}
        </div>
        <Footer />
        </body>
    </html>
  )
}
